### ISSUE TITLE
Is it good idea to see  dmesg logs without sudo/root acces?

### ISSUE THREAD

**Issue by denisgolius** [polyverse/rmesg#13]
Is it good idea to see  dmesg logs without sudo/root acces? I mean that all linux distributions accept fix that this info could be dangerous for hackers/etc...

**Comment by archisgore** [comment]
IMO, all systems should be least-privilege at all levels.

Fortunately I've not come across a distro that allows this at all. We run a large testbed across some 20+ish distros/versions and all of them require root to access the buffer. So all good there IMO.

Keep in mind that dmesg/rmesg don't enforce those permissions - they're enforced at a lower level than that. So rmesg/dmesg cannot show kernel logs to unauthorized/non-root users. 

The tools themselves simply pull logs from either the /dev/kmsg file or using the klogctl syscall - both of which require root access.
