### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by x10an14** [polyverse/rmesg#2]
Hi!

Rust newbie here, is it an easy question to answer whether or not this library uses/is intended to be used with async Rust?

My use-case is filtering specific kernel logs, and converting them to JSON format.

**Comment by archisgore** [comment]
Yes, since the entire library is synchronous (and has no threads), it should be easy to consume this from Async code.

**Comment by x10an14** [comment]
Awesome!

With the `RMesgLinesIterator`, how could we have it async await next kernel / syslog msg?

I'm hoping for something like (if written with the rust `loop` construct):

```rust
loop {
  let next_line: String = rmesg::get_next_line_async().await?;
  // Perform operation/filter/json conversion
}
```

**Comment by x10an14** [comment]
As opposed to something like this:

```rust
loop {
  for line in RMesgLinesIterator::with_options(false, SUGGESTED_POLL_INTERVALL)? {
    // do stuffs
  }
  // sleep async a random time, making this a busy poll instead of lazy async
}
```

**Comment by archisgore** [comment]
I know what you're saying.. and you've recognized the same problem I ran into. You see - the kernel has no async interface by lines (at least, not when reading through `klogctl`)

There IS however a way to do what you say, and I need to bring that code into `rmesg`, and that is to tail the `/dev/kmsg` device file as is done here: https://github.com/polyverse/zerotect/blob/master/src/monitor/dev_kmsg_reader.rs#L234

In which case it can be made async so long as the underling file reader is async.

But you should be able to do that yourself - there's really no need to go through rmesg for that - use standard file API to read line by line. In ZeroTect I do something like this: https://github.com/polyverse/zerotect/blob/master/src/monitor/mod.rs#L54

Which basically first attempts to read the file (which is not available on older distros or doesn't work well, i.e. CentOS 6), and if that fails goes to rmesg reader.

**Comment by x10an14** [comment]
Thanks so much for feedback and tips! Much appreciated =)

**Comment by x10an14** [comment]
Closing issue for my own sake, will go the `dev/kmsg` route instead (as suggested).

**Comment by archisgore** [comment]
Just an FYI - rmesg now supports a first-class async interface. When reading klogctl it's still "synchronous" on the back side and requires polling (kind of how hyper also has to run a thread for some OS-level synchronous APIs), but on the front side it's fully async. It also transparently supports tailing `/dev/kmsg` when that file is available and readable (on newer kernels). In that case it's fully async.
